name         'puppet-github'
version      '1.0.3'
source       'http://github.com/rynr/puppet-github'
author       'Rainer Jung'
license      'GPL'
summary      'Download tarballs from github'
project_page 'http://rynr.github.com/puppet-github'
